version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: imdc_db
      POSTGRES_USER: imdc_user
      POSTGRES_PASSWORD: imdc_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
