name: Django CI (SQLite)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run migrations
        run: pipenv run python manage.py migrate

      - name: Run tests
        id: tests
        run: pipenv run python manage.py test | tee result.log

      # Upload test log as artifact (for debugging if tests fail)
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: result.log

      # Comment summary on PR
      - name: Post test summary
        if: github.event_name == 'pull_request'
        run: |
          echo "### ✅ Django CI Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Python version: 3.13" >> $GITHUB_STEP_SUMMARY
          echo "- Database: SQLite" >> $GITHUB_STEP_SUMMARY
          echo "- Migration & Tests: Completed" >> $GITHUB_STEP_SUMMARY
